apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ansible-builder
spec:
  description: >-
    This task will use ansible-builder to creat (not build) an Ansible Execution Environment.
  workspaces:
    - name: ee-repo
      description: The source workspace where the Execution Environment code is cloned.
  params:
    - description: ansible-builder output verbosity
      name: VERBOSITY
      type: string
      default: "2"
    - name: BUILDER_IMAGE
      description: The location of the ansible-builder image.
      type: string
      default: quay.io/ansible/ansible-builder:latest
    - name: OUTPUT_FILE
      description: Output of the ansible-builder, either Dockerfile or Containerfile.
      type: string
      default: Containerfile
  steps:

    - name: ansible-builder-create
      workingDir: $(workspaces.ee-repo.path)
      image: $(params.BUILDER_IMAGE)
      script: |
        #!/bin/sh
        set -eux -o pipefail

        env

        ansible-builder create -v "$(params.VERBOSITY)" --output-filename "$(params.OUTPUT_FILE)"